### ISSUE TITLE
Add support to sirupsen/logrus

### ISSUE THREAD

**Issue by EtienneM** [timonwong/loggercheck#50]
Would you consider adding the support for https://github.com/sirupsen/logrus/ in this linter? Is it easy to add the support for a new logging library and would you consider an external contribution for it? From the PR #30, I think that a new logging lib could easily be added.

We extensively use this logging library and would love to see the support for it in your linter :)

Thanks

**Comment by timonwong** [comment]
I think it's no need to add such checker for logrus. The key value pairs in logrus is special, for example:

```go
log.WithFields(log.Fields{
    "animal": "walrus",
  }).Info("A walrus appears")
```

The definition for `log.Fields`:

```
type Fields map[string]interface{}
```

You can see its a map (which there is no need to check odd pairs of key values), and the may key is already "string" (no need to check the key type)

**Comment by EtienneM** [comment]
I may be confused by the purpose of this linter. If that's the case, I'm sorry about it. Is your linter able to detect the two following errors?

```go
log.Infof("A %v appears")
log.Info("A %v appears", "walrus")
```

**Comment by timonwong** [comment]
> I may be confused by the purpose of this linter. If that's the case, I'm sorry about it. Is your linter able to detect the two following errors?
> 
> ```go
> log.Infof("A %v appears")
> log.Info("A %v appears", "walrus")
> ```

I think it can be archived by the govet:
- https://golangci-lint.run/usage/linters/#govet

**Comment by EtienneM** [comment]
Interesting, thanks :+1:
