### ISSUE TITLE
Question about how could loggercheck detect this line is for logging?

### ISSUE THREAD

**Issue by fovgrubby128** [timonwong/loggercheck#60]
I read the code, and found it would check for the function is variadic, and last argument is `...interface{}`, but I'm curious whether it's sufficient to identify the function is used for logging?

**Comment by timonwong** [comment]
It also checks the package name and type name, which are covered in rules, here is static rules for example:  https://github.com/timonwong/loggercheck/blob/0d153ec073271953f8250b580ed4f7e6bed804e7/staticrules.go
